on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - name: Publish lib
      run: cargo publish
      working-directory: ./lib
    - name: Sleep for 15 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - name: Publish cli
      run: cargo publish
      working-directory: ./cli
    - name: Build
      uses: docker://untoldwind/rust-musl-builder:v1.52.0
      with:
        args: cargo build --release
    - name: Copy binary
      run: cp ./target/x86_64-unknown-linux-musl/release/acari ./target/acari
      working-directory: .
    - name: Strip binary
      run: strip ./target/acari
      working-directory: .
    - name: Create sha256sum
      run: sha256sum acari > acari.sha256sum
      working-directory: ./target
    - name: Gzip
      run: gzip ./target/acari
      working-directory: .
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ""
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./target/acari.gz
        asset_name: acari.gz
        asset_content_type: application/gzip
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./target/acari.sha256sum
        asset_name: acari.sha256sum
        asset_content_type: text/plain
